platform :ios, ‘8.0’

target "NoverReader" do
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 0.6.4'
pod 'MJExtension', '~> 3.0.10'
pod 'ReactiveCocoa', '~> 2.5'
pod 'UMengAnalytics'
pod 'FMDB'
pod 'LSStatusBarHUD'
pod 'SVProgressHUD'
pod 'SSZipArchive'

end
